version: 0.2

env:
  variables:
    ECR_REPOSITORY: 185430064325.dkr.ecr.us-west-2.amazonaws.com/cloud-tech-ecr

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      #- aws ecr get-login-password --region us-west-2 | docker login --username learning-user1 --password-stdin ${ECR_REPOSITORY}
      -  aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 185430064325.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t container-test-app .
      - docker tag container-test-app:latest ${ECR_REPOSITORY}:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push ${ECR_REPOSITORY}:latest
      - echo Build completed on `date`
      - echo Creating imagedefinitions.json...
      - |
        echo '[
          {
            "name": "container-test-app",
            "imageUri": "'${ECR_REPOSITORY}':latest"
          }
        ]' > imagedefinitions.json
      - echo imagedefinitions.json created.

artifacts:
  files:
    - imagedefinitions.json
